# Generated by Django 4.1.7 on 2023-04-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='goodschannelgroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='频道组名'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='caption',
            field=models.CharField(max_length=1000, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=500, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='name',
            field=models.CharField(max_length=500, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='spuspecification',
            name='name',
            field=models.CharField(max_length=200, verbose_name='规格名称'),
        ),
    ]
