# Generated by Django 4.1.7 on 2023-04-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_brand_name_alter_goodscategory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsvisitcount',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='goodsvisitcount',
            name='update_time',
        ),
    ]
