# Generated by Django 4.1.7 on 2023-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_goodsvisitcount_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsvisitcount',
            name='create_time',
            field=models.DateTimeField(default='', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='goodsvisitcount',
            name='update_time',
            field=models.DateTimeField(default='', verbose_name='更新时间'),
        ),
    ]
